[project]
name = "text-diffusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.6.0",
    "torch>=2.7.0",
    "transformers>=4.52.3",
]
